folder_tst: /home/user/tst
folder_in: /home/user2/tst/file
folder_out: /home/user2/tst/out
folder_ext: /home/user2/tst/ext
folder_ext2: /home/user2/tst/ext2
folder_badarx: /home/user2/tst/badarx
count: 5
size_of_file: 1
name_of_arch: '*.7z'
path_journal: /home/user/journal.txt
host: 0.0.0.0
user: user2
password: "2222"
local_path: /home/user/p7zip-full.deb
remote_path: /home/user2/p7zip-full.deb
pkgname: p7zip-full